name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from plugin header
        id: version
        run: |
          VERSION=$(grep -oP "Version:\s*\K[0-9]+\.[0-9]+\.[0-9]+" wp-site-manager.php)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.version.outputs.version }} does not exist, will create release"
          fi

      - name: Create ZIP archive
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          mkdir -p /tmp/wp-site-manager
          cp -r . /tmp/wp-site-manager/
          rm -rf /tmp/wp-site-manager/.git /tmp/wp-site-manager/.gitea
          cd /tmp && zip -r $GITHUB_WORKSPACE/wp-site-manager-${{ steps.version.outputs.version }}.zip wp-site-manager

      - name: Create tag and release
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          # Create tag
          git config user.name "gitea-actions"
          git config user.email "actions@gobird.io"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

          # Create release using Gitea API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\": \"v$VERSION\", \"name\": \"v$VERSION\", \"body\": \"Release v$VERSION\", \"draft\": false, \"prerelease\": false}" \
            "$GITHUB_SERVER_URL/api/v1/repos/$GITHUB_REPOSITORY/releases"

          # Get release ID
          RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "$GITHUB_SERVER_URL/api/v1/repos/$GITHUB_REPOSITORY/releases/tags/v$VERSION" | jq -r .id)

          # Upload asset
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/zip" \
            --data-binary "@wp-site-manager-$VERSION.zip" \
            "$GITHUB_SERVER_URL/api/v1/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=wp-site-manager-$VERSION.zip"
